#!/bin/sh -e

# File: bootstrap
#
# Description: This script runs the GNU Autotools to generate the
# configure script.  You only need to run this script if the configure
# script is not present, or if you have changed configure.in,
# acinclude.m4, acconfig.h, or Makefile.am. You must have GNU M4,
# Autoconf, Automake, and possibly Libtool installed in order to run
# this script.

# install all deps from config/deps.py before startings this script
ln -sf /usr/share/libtool/build-aux/ltmain.sh .
aclocal
autoheader
automake --add-missing --warnings=none
autoconf
./configure
make
